# Generated by Django 5.2.7 on 2025-10-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.URLField(default='/events', help_text='URL to redirect the user when they click this notification', max_length=500),
        ),
    ]
