# Generated by Django 5.2.7 on 2025-10-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.URLField(default='http://localhost:8000/events', help_text='URL to redirect the user when they click this notification', max_length=500),
        ),
    ]
