# Generated by Django 5.2.7 on 2025-11-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_bio_alter_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_calendar_public',
            field=models.BooleanField(default=True),
        ),
    ]
