from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# Note: Fields relate to specific form inputs
#       egs: TextField -> textarea, CharField -> input of type text


class Event(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()

    # event_id generated by event_modal
    event_id = models.SlugField(null=True, unique=True)

    # Date timestamp added every event creation
    date = models.DateTimeField(auto_now_add=True)

    # Split from datetime-local in modal
    start_date = models.DateField()
    start_time = models.TimeField()
    end_date = models.DateField()
    end_time = models.TimeField()

    def __str__(self):
        return self.title


# Create your models here.


class Participation(models.Model):
    STATUS_CHOICES = [
        ('yes', 'Yes'),
        ('no', 'No')
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(
        Event, on_delete=models.CASCADE, related_name='participations')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES)

    class Meta:
        unique_together = ('user', 'event')  # user can only RSVP once

    def __str__(self):
        return f"{self.user.username} → {self.event.title} ({self.status})"


class BusyTime(models.Model):
    DAYS_OF_WEEK = [
        (0, 'Monday'),
        (1, 'Tuesday'),
        (2, 'Wednesday'),
        (3, 'Thursday'),
        (4, 'Friday'),
        (5, 'Saturday'),
        (6, 'Sunday'),
    ]

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='busy_times')
    day_of_week = models.IntegerField(choices=DAYS_OF_WEEK)
    start_time = models.TimeField()
    end_time = models.TimeField()
    description = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return f"{self.user.username}: {self.get_day_of_week_display()} {self.start_time}-{self.end_time}"


class AvailabilityBlock(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    start = models.DateTimeField()
    end = models.DateTimeField()

    def __str__(self):
        return f"{self.user.username} — {self.event.title} ({self.start} → {self.end})"
