# Generated by Django 5.2.7 on 2025-11-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_end_date_event_end_time_event_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
